
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import api from '../api';
import { useAuth } from '../AuthContext';
import type { WorkoutTemplate, CompletedExercise, ExerciseDefinition, ExerciseSet } from '../types';
import ExerciseLogger from '../components/ExerciseLogger';
import AddExerciseToWorkoutModal from '../components/AddExerciseToWorkoutModal';

interface LocationState {
    template?: WorkoutTemplate;
}

const ActiveWorkoutPage: React.FC = () => {
    const { templateId } = useParams<{ templateId?: string }>();
    const navigate = useNavigate();
    const location = useLocation();
    const { userId } = useAuth();

    const [workoutName, setWorkoutName] = useState('New Workout');
    const [exercises, setExercises] = useState<CompletedExercise[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState('');
    const [showAddExerciseModal, setShowAddExerciseModal] = useState(false);

    useEffect(() => {
        const initializeWorkout = async () => {
            setError('');
            setIsLoading(true);
            try {
                let initialExercises: CompletedExercise[] = [];
                let name = 'New Workout';

                if (templateId) {
                    const response = await api.get<WorkoutTemplate>(`/templates/${templateId}`);
                    const template = response.data;
                    name = template.name;
                    initialExercises = template.exercises.map((def: ExerciseDefinition) => ({
                        id: '', // Will be generated by backend
                        exerciseDefinitionId: def.id,
                        exerciseName: def.name,
                        sets: [],
                    }));
                } else if (location.state) {
                    const state = location.state as LocationState;
                    if (state.template) {
                        const template = state.template;
                        name = template.name;
                        initialExercises = template.exercises.map((def: ExerciseDefinition) => ({
                            id: '', // Will be generated by backend
                            exerciseDefinitionId: def.id,
                            exerciseName: def.name,
                            sets: [],
                        }));
                    }
                }
                
                setWorkoutName(name);
                setExercises(initialExercises);

            } catch (err: unknown) {
                console.error('Error initializing workout:', err);
                if (typeof err === 'object' && err !== null && 'response' in err && typeof (err as any).response === 'object' && (err as any).response !== null && 'data' in (err as any).response) {
                    setError((err as any).response.data || 'Failed to initialize workout.');
                } else {
                    setError('Failed to initialize workout.');
                }
            } finally {
                setIsLoading(false);
            }
        };

        initializeWorkout();
    }, [templateId, location.state]);

    const handleSetsChange = (index: number, newSets: ExerciseSet[]) => {
        const updatedExercises = [...exercises];
        updatedExercises[index].sets = newSets;
        setExercises(updatedExercises);
    };

    const handleAddExerciseToSession = (exerciseDef: ExerciseDefinition) => {
        if (!exercises.some(e => e.exerciseDefinitionId === exerciseDef.id)) {
            const newCompletedExercise: CompletedExercise = {
                id: '', // Backend will generate
                exerciseDefinitionId: exerciseDef.id,
                exerciseName: exerciseDef.name,
                sets: [],
            };
            setExercises([...exercises, newCompletedExercise]);
        }
    };

    const handleSaveWorkout = async () => {
        setError('');
        if (exercises.every(ex => ex.sets.length === 0)) {
            setError('Cannot save an empty workout. Add some sets!');
            return;
        }

        try {
            const newWorkoutSession = {
                date: new Date().toISOString(),
                completedExercises: exercises.map((ex: CompletedExercise) => ({
                    exerciseDefinitionId: ex.exerciseDefinitionId,
                    exerciseName: ex.exerciseName,
                    sets: ex.sets.map((set: ExerciseSet) => ({ reps: set.reps, weight: set.weight }))
                }))
            };
            await api.post('/workouts', newWorkoutSession);
            navigate('/history'); // Redirect to history page
        } catch (err: unknown) {
            console.error('Failed to save workout:', err);
            if (typeof err === 'object' && err !== null && 'response' in err && typeof (err as any).response === 'object' && (err as any).response !== null && 'data' in (err as any).response) {
                setError((err as any).response.data || 'Failed to save workout.');
            } else {
                setError('Failed to save workout.');
            }
        }
    };

    if (isLoading) {
        return <p>Loading workout...</p>;
    }

    return (
        <div style={{ maxWidth: '800px', margin: '50px auto', padding: '20px', border: '1px solid #ccc', borderRadius: '8px' }}>
            <h2>{workoutName}</h2>
            {error && <p style={{ color: 'red' }}>{error}</p>}

            {exercises.length === 0 && !isLoading && (
                <p>No exercises in this workout. Add some to get started!</p>
            )}

            {exercises.map((exercise, index) => (
                <ExerciseLogger
                    key={exercise.exerciseDefinitionId} // Unique key for each exercise in session
                    exerciseDefinition={{
                        id: exercise.exerciseDefinitionId,
                        name: exercise.exerciseName,
                        description: '', // Not strictly needed here, but part of interface
                        userId: userId || '' // Placeholder
                    }}
                    initialSets={exercise.sets}
                    onSetsChange={(newSets: ExerciseSet[]) => handleSetsChange(index, newSets)}
                />
            ))}

            <button onClick={() => setShowAddExerciseModal(true)} style={{ marginTop: '20px', padding: '10px 15px', backgroundColor: '#007bff', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
                Add Another Exercise
            </button>
            <button onClick={handleSaveWorkout} style={{ marginTop: '20px', marginLeft: '10px', padding: '10px 15px', backgroundColor: '#28a745', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
                Finish Workout
            </button>
            <button onClick={() => navigate('/')} style={{ marginTop: '20px', marginLeft: '10px', padding: '10px 15px', backgroundColor: '#dc3545', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
                Cancel Workout
            </button>

            <AddExerciseToWorkoutModal
                isOpen={showAddExerciseModal}
                onClose={() => setShowAddExerciseModal(false)}
                onAddExercise={handleAddExerciseToSession}
                existingExerciseIds={new Set(exercises.map(ex => ex.exerciseDefinitionId))}
            />
        </div>
    );
};

export default ActiveWorkoutPage;
